<?php

namespace frontend\modules\backend\models;

use Yii;
use yii\base\Model;
use yii\helpers\DateTime;
use common\models\News;
use common\models\PriorityList;

class RightsForm extends Model
{
    public $rights = [];
    public $account;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rights'], 'safe'],
            ['account', 'required'],
            ['rights', 'required', 'message' => '至少分配一个权限']
         ];
    }

    public function setRights(){
        $count = PriorityList::deleteAll(['account' => $this->account]);
        for ($i = 0; $i < sizeof($this->rights); $i++) {
                $grantPriority = new PriorityList();
                $grantPriority->account = $this->account;
                $grantPriority->priority = $this->rights[$i];
                $grantPriority->save();
            
            
        }
        return true;
    }


    public function beforeSave($insert) {
        if($this->rights) {
            $this->rights = implode(',',$this->rights);
     
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
     
    public function afterFind() {
        $this->rights = explode(',',$this->rights);
        parent::afterFind();
    }

    
}